language: python

python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

cache: pip

install:
  - pip install -r requirements.txt
  - pip install codecov

env:
  -CODECOV_TOKEN="CODECOV_TOKEN"

before_script: cd tests

script:
  - python test_base.py
  - python test_utils.py
  - coverage run test_base.py

after_success:
  - codecov